version: '2'
services:
  'image-service':
      build:
          dockerfile: dev.Dockerfile
          context: .
      image: image-service
      env_file: ../default.env
      environment:
        - GOOGLE_SEARCH_API_KEY=${GOOGLE_SEARCH_API_KEY}
        - GOOGLE_SEARCH_API_CX=${GOOGLE_SEARCH_API_CX}
      volumes:
          - ../:/var/go/src/github.com/eggsbenjamin/image-service
